name: Subir nueva 

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Conncet to ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - uses: actions/checkout@v4
      - name: Copy file via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_CUCA }}
          username: ${{ secrets.USER_CUCA }}
          password: ${{ secrets.PASS_CUCA }}
          port: 22
          timeout: 120s
          overwrite: true
          source: ".,!.git"
          target: ~/
